import { Permission, Role } from './types';

export const ROLE_PERMISSIONS_MAP: Record<Role, Permission[]> = {
  OWNER: [
    'VIEW_EVENTS',
    'EDIT_INVESTIGATIONS',
    'ASSIGN_TASKS',
    'MANAGE_MEMBERS',
    'MANAGE_WATCHLISTS',
    'EXPORT_REPORTS',
    'DELETE_COMMENTS',
    'MANAGE_ORGANIZATION',
    'INVITE_MEMBERS',
    'CONFIGURE_ALERTS'
  ],
  ADMIN: [
    'VIEW_EVENTS',
    'EDIT_INVESTIGATIONS',
    'ASSIGN_TASKS',
    'MANAGE_MEMBERS',
    'MANAGE_WATCHLISTS',
    'EXPORT_REPORTS',
    'DELETE_COMMENTS',
    'INVITE_MEMBERS',
    'CONFIGURE_ALERTS'
  ],
  MANAGER: [
    'VIEW_EVENTS',
    'EDIT_INVESTIGATIONS',
    'ASSIGN_TASKS',
    'MANAGE_WATCHLISTS',
    'EXPORT_REPORTS',
    'CONFIGURE_ALERTS'
  ],
  ANALYST: [
    'VIEW_EVENTS',
    'EDIT_INVESTIGATIONS',
    'ASSIGN_TASKS',
    'EXPORT_REPORTS',
    'CONFIGURE_ALERTS'
  ],
  RESEARCHER: [
    'VIEW_EVENTS',
    'EDIT_INVESTIGATIONS',
    'EXPORT_REPORTS'
  ],
  VIEWER: [
    'VIEW_EVENTS',
    'EXPORT_REPORTS'
  ],
  GUEST: [
    'VIEW_EVENTS'
  ]
};
